language: php

env:
  global:
    - secure: "A/hmkGXESJewohkPLJQqS4Sa4jRP8VSjZ2Gle9hNVRAVBEsjIgXQ6iB2kTTbqM4PBgpTJ/9WYvO1Rl8zDpONBvcK3wHaviVUiwzrM/qW0DVVmHiPDoHgEWCU/O7xF2+OaDtrF1oSKxYRMSaNZ0b5bAbwg9cI/WYWgHpRrOgq8HNST2ALgB3h9AS6HE7oMCsuvhkBo+zKb4BO2Kf/vufhaY52rlMVNHN72YMd1vbqDFDJRRYJ3FqojE+hOdhZoIKkcZchAtM5pHeFpi6fvZYPXR26m6Yazb9SWcWkGW/j0Hv+RM6BHSzg71guR3IMt/eTLZOYuAgoUpUZI4myBNRyYZtsnqd7HMmdIyDzZiPYynBlKoB9xseO0T6QcB0RKprThsv2begsB8s0V7kG6bpzndDZD5XxTVPpkJrvoyCG8XX5Yc1NfmUucEqlwyXKQOHhsHM3zK6EdloRQmoH8phzAXTP6d0RYZVMAA+w0yvdFhx09rbS2ESKYT+Czp+BrE3RauYZXcflG4wt6W5j2HqDj1rM0kVh6lQmP6sdNvopMHGq1APLFMj/mbPpSF7uFq+3JSlER6/vKea2pATZ2GUiy87aQtyyi1oOzIvnSqDUCAMNtqr7VvpRg9aVzssJuc7g6b1cBMPRPcHMl8CpVVEFGn3fJKt50kl+YE8W5txCLmQ="

cache:
  directories:
    - $HOME/.composer/cache
    - .build/php-cs-fixer
    - .build/phpstan
    - .build/phpunit

stages:
  - style
  - stan
  - test
  - infection

jobs:
  include:
    - stage: Style

      php: 7.3

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate --strict
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p .build/php-cs-fixer

      script:
        - composer normalize --dry-run

    - stage: Stan

      php: 7.3

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate --strict
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p .build/phpstan

      script:
        - vendor/bin/phpstan analyse --configuration=phpstan.neon

    - &TEST

      stage: Test

      php: 7.3

      env: WITH_LOWEST=true

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate --strict
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; fi
        - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
        - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

      before_script:
        - mkdir -p .build/phpunit

      script:
        - vendor/bin/phpunit --configuration=test/AutoReview/phpunit.xml
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --dump-xdebug-filter=.build/phpunit/xdebug-filter.php; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi
        - vendor/bin/phpunit --configuration=test/Integration/phpunit.xml

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi

    - <<: *TEST

      php: 7.3

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.3

      env: WITH_HIGHEST=true

    - stage: Infection

      php: 7.3

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate --strict
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p .build/infection
        - xdebug-enable

      script:
        - vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100

notifications:
  email: false
