# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - push

name: "JS Information"

jobs:
  php:
    name: "JS Information"

    runs-on: ubuntu-latest

    steps:
      - name: "Node version"
        run: $(which node) --version

      - name: "NPM version"
        run: $(which npm) --version

      - name: "Yarn version"
        run: $(which yarn) --version
